### ISSUE TITLE
[pgks] Contract returning an uninitialized string or tuple with string throws panic

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#1047]
Eris Version 0.12.0-rc3

When returning a string from a contract that has not been initialized, i.e. is empty throws a panic.
Two ways this seems reproducible:
1. Create a contract with a string storage variable; don't set a value. Then call a `getVariable()` that returns it
2. Create a contract with a function that returns a tuple containing a string, e.g. `function test() returns (string, address)`. Returning the tuple `("bla", address(this))` triggers the error. This does not happen using other simple data types! It also does not happen when returning ONLY a string.

```
                                         addr=5F9C13864673057447D39F951CA1B2FD3F36B070
Executing Job                                 getName
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x5614486cf560, 0xc4200140d0)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi.unpackByteArray(0xc420448700, 0x20, 0x40, 0x40, 0xc4202ca401, 0x0, 0x0)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi/abi.go:401 +0x5fa
github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi.UnpackProcessType(0xc4202cb348, 0x6, 0xc420448700, 0x20, 0x40, 0x0, 0x58, 0x58, 0x0)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi/abi.go:343 +0xada
github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi.ABI.UnPack(0xc420187410, 0xc420492040, 0x7, 0xc420448700, 0x40, 0x40, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/abi/abi.go:293 +0x57b
github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/core.UnPacker(0xc420469400, 0x7d4, 0x9d4, 0xc420492040, 0x7, 0xc42049ca00, 0x80, 0x0, 0x0, 0xc4207b8000, ...)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/eris-ltd/eris-abi/core/core.go:91 +0xe3
github.com/eris-ltd/eris-pm/util.ReadAndDecodeContractReturn(0xc420492020, 0x9, 0xc420492040, 0x7, 0xc42049ca00, 0x80, 0xc42044f9e0, 0xc4202ca640, 0x4, 0x4, ...)
    /go/src/github.com/eris-ltd/eris-pm/util/readers.go:81 +0x243
github.com/eris-ltd/eris-pm/perform.QueryContractJob(0xc4204b11f0, 0xc42044f9e0, 0x56144812f3cc, 0xd, 0x0, 0x0, 0x1, 0x0, 0x0)
    /go/src/github.com/eris-ltd/eris-pm/perform/jobs_test_jobs.go:69 +0xf1e
github.com/eris-ltd/eris-pm/perform.RunJobs(0xc42044f9e0, 0x12, 0xc42046d590)
    /go/src/github.com/eris-ltd/eris-pm/perform/job_manager.go:97 +0x565
github.com/eris-ltd/eris-pm/packages.RunPackage(0xc42044f9e0, 0x561448130556, 0xf)
    /go/src/github.com/eris-ltd/eris-pm/packages/run_package.go:19 +0x3d
github.com/eris-ltd/eris-pm/cmd.RunPackage(0x5614489fd760, 0xc4200768c0, 0x0, 0x14)
    /go/src/github.com/eris-ltd/eris-pm/cmd/eris-pm.go:101 +0x2f
github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra.(*Command).execute(0x5614489fd760, 0xc42000c170, 0x14, 0x15, 0x5614489fd760, 0xc42000c170)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra/command.go:603 +0x43b
github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5614489fd760, 0x52, 0x94, 0xc420070000)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra/command.go:689 +0x369
github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra.(*Command).Execute(0x5614489fd760, 0xc42044f9e0, 0xc4200e7f80)
    /go/src/github.com/eris-ltd/eris-pm/vendor/github.com/spf13/cobra/command.go:648 +0x2d
github.com/eris-ltd/eris-pm/cmd.Execute()
    /go/src/github.com/eris-ltd/eris-pm/cmd/eris-pm.go:71 +0x7f
main.main()
    /go/src/github.com/eris-ltd/eris-pm/cmd/eris-pm/main.go:8 +0x16
```

**Comment by VoR0220** [comment]
If this is related to this being in the constructor, this bug is related. https://github.com/ethereum/solidity/issues/583

**Comment by VoR0220** [comment]
Closing as related to constructor "features" of the EVM.
