### ISSUE TITLE
Chain stops making blocks 

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-cli#1138]
- [1.12.3, ] `docker version`
- [0.12.0 ] `eris version`
- [0.8.2 ] `docker-machine version`
- [linux ] operating system details 

I don't know the specific point where it is failing but when I do lots of transactions in the chain like 50 transactions say at a time, after a point chain stops creating blocks. Logs in the validator machines are as follows: 

enterPropose: Error signing proposal     module=consensus height=82511 round=0 error="Attempt of duplicate signing of proposal: Height 82511, Round 0"

EROR[12-14|05:56:05] Error with msg                           module=consensus type=*consensus.ProposalMessage peer=CF2A1540EC2ADBE520A904FFB8723BCFF9959D6909DC8CA79D4725D4CFC8714A error="Error invalid proposal signature" msg="[Proposal Proposal{82511/0 PartSet{T:1 26830F519835} -1 /5E97A61BFFB6.../}]"

WARN[12-14|05:56:11] Found conflicting vote from ourselves. Did you unsafe_reset a validator? module=consensus height=82511 round=0 type=2

Is there any specific reason for this behavior??

**Comment by zramsay** [comment]
Hi @somak12 thanks for the bug report. We've seen similar behaviour pop up recently. Can you provide more details on how you created/started your chain? pinging @benjaminbollen for review of eris-db logs

**Comment by somak12** [comment]
@zramsay I created chain with 1 root account + 4 participants + 3 validators. Im using docker machines(amazon driver) for the validators. As you can see things were working fine till height 82510. One thing is that after work I used to stop the chain and the eris service and restart it back when needed.

**Comment by somak12** [comment]
And Im uisng image = "quay.io/eris/db:0.12.1" for issue of chain not creating blocks due to use of curent timestamp in the contract..

**Comment by andytudhope** [comment]
I am having exactly the same issue. tried to leave a chain running over the weekend to test how big it would get and returned to find this message in the logs. Cleaning Eris and restarting the chains does nothing for me - still get `Found conflicting vote from ourselves. Did you unsafe_reset a validator?` in the logs.

[1.12.5 ] `docker version`
[0.12.0] `eris version`
[Mac El Capitan] `OS`

**Comment by marc4gov** [comment]
Look like I have something similar. I start 4 validators, that's ok. Then I start the root machine, looks like the chain is running (Height is increasing) but actually not making blocks. Logs shows messages like these:

```
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=0
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[HasVote VI:2 V:{60/00/2} VI:2]"
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=2
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:60 R:0 S:RoundStepPrecommitWait LCR:0]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[HasVote VI:3 V:{60/00/2} VI:3]"
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=3
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:60 R:0 S:RoundStepCommit LCR:0]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[CommitStep H:60 BP:PartSet{T:1 9D7FFA8570E2} BA:BA{1:X}]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:61 R:0 S:RoundStepNewHeight LCR:0]"
```

after several restarts, the chain is finally catching up (with WARN signals, but that's because it has to sync I guess), but looks unstable. Deploying contracts is going OK, but later on, the chain stops and I get the same message as Andy and somak12 are getting. At that point I just can't manage the chain getting up again for the root machine.

The validators seem Ok though. This is my setup:

```
#!/usr/bin/env bash
echo "Running HerenBouwChain environment setup..."
chainName=herenbouwchain

for i in `seq 0 3`
do
  eris chains rm -xf $chainName --machine "do-val$i"
  eris chains start --init-dir "${chainName}"/"${chainName}_validator_00$i" --machine "do-val$i" $chainName
  echo "Wait for do-val$i to start $chainName.."
done

eris chains rm -xf $chainName --machine do-prod0
eris chains start --init-dir "${chainName}"/"${chainName}_root_000" --machine do-prod0 $chainName
echo "Wait for do-prod0 to start $chainName.."
```

**Comment by marc4gov** [comment]
Bummer: I managed to get the chain going on do-prod0, but now it chokes on deploying contracts.
Log output: 

```
INFO[01-20|15:52:55] Receive                                  module=consensus src="Peer{MConn{188.166.67.157:46656} 4EDF0E802BF1 out}" chId=22 msg="[Vote VI:3 V:Vote{121/00/1(Prevote) 5C0CBA203EEA#PartSet{T:1 AAC9ED6FC64B} /97044898A9F8.../} VI:3]"
INFO[01-20|15:52:55] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.67.157:46656} 4EDF0E802BF1 out}" peerRound=0 height=121 round=0 prevotes=BA{4:XX_X} index=3
INFO[01-20|15:52:55] Added to prevote                         module=consensus vote="Vote{121/00/1(Prevote) 5C0CBA203EEA#PartSet{T:1 AAC9ED6FC64B} /97044898A9F8.../}" prevotes="VoteSet{H:121 R:0 T:1 +2/3:true BA{4:XX_X}}"
INFO[01-20|15:52:55] enterPrecommit(121/0). Current: 121/0/RoundStepPrevote module=consensus
NOTE[01-20|15:52:55] enterPrecommit: +2/3 prevoted proposal block. Locking module=consensus hash=5C0CBA203EEA74D42047BD14081FC1F8CFC9570B
panic: Paniced on a Consensus Failure: enterPrecommit: +2/3 prevoted for an invalid block: Wrong Block.Header.AppHash.  Expected B9E9A513B59FC0FF44D3E3C35F489EA55C460661, got 6425B68E61D99AA5E483219DAA1EE837F250400C

goroutine 33 [running]:
panic(0x55603e88dcc0, 0xc421cd8090)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common.PanicConsensus(0x55603e88dcc0, 0xc421cd8070)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common/errors.go:39 +0xe2
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrecommit(0xc42011c480, 0x79, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1070 +0x14f7
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc42011c480, 0x3, 0xc421cc17a0, 0xc420185080, 0x40, 0xc422347a00, 0x0, 0x0, 0xc422347a80, 0x55603dcffc47, ...)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1440 +0x113a
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc42011c480, 0x3, 0xc421cc17a0, 0xc420185080, 0x40, 0x0, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1358 +0x76
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc42011c480, 0x55603e8b9620, 0xc421ccc8b0, 0xc420185080, 0x40, 0x79, 0x0, 0x4, 0xed0142956, 0x394e61d0, ...)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:668 +0x66d
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc42011c480, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:614 +0x2c9
created by github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).startRoutines
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:320 +0x6d
```

**Comment by zramsay** [comment]
replaced by https://github.com/eris-ltd/eris-db/issues/457 since this is an eris-db/tendermint panic
