### ISSUE TITLE
RPC crashing on high load

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#471]
I am pushing a lot of data via a minimal node.js frontend into a minimal contract (looping int values as fast as node can and overwriting a single variable in the contract). While that probably doesnt make sense, it would be nicer to get a more graceful shutdown or overload behavior of the RPC than this:

[JSON RPC 2.0 Error] Message Id: 1664, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 36359, expected 39112
/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:116
        data2 = data2[1];
                     ^

TypeError: Cannot read property '1' of undefined
    at fixedCallback (/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:116:22)
    at /home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:79:13
    at httpRequest.onreadystatechange (/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/someone/.eris/apps/idi/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)

**Comment by SCBuergel** [comment]
I followed the examples in [making my chain](https://docs.erisindustries.com/tutorials/chainmaking/) and did the following minimal modifications to the [IdisContract](https://docs.erisindustries.com/tutorials/contractsdeploying/)

idi.sol:

    uint val;
    uint count;

    function setAndIncrement(uint newVal) {
      val = newVal;
      count++;
    }

app.js:

    for(var c = 0; c < count; c++)
    {
      idisContract.setAndIncrement(c, function(error, result){
        if (error) { console.log(error); }
      });
    }

For large values of `count` (typically above 1000), I get the above mentioned error.

**Temporary fix** [ugly hack since we will loose the corresponding transaction(s)!]: I replaced line 116 in unsafe.js:

    data2 = data2[1];

with

    if (data2)
      data2 = data2[1];
    else
      console.log("Warning: data2[1] undefined! error: [[[" + error + "]]]");

**Comment by ebuchman** [comment]
tagging @NodeGuy re making the js exit more gracefully.

As for the nonce issue, are you doing this on a single node or on a network? 

Running something similar locally I'm actually having a different issue, where I get lots of ECONNRESET. At first the erisdb was crashing due to too many open file descriptors which could be fixed by increasing the per process limit. Now I'm not entirely sure what's happening, need to investigate further

**Comment by ebuchman** [comment]
So I think part of the problem here may be that currently eris-contracts.js (through erisdb.js) hangs on every single tx waiting for it to be included in a block, so when you send a thousand txs, those HTTP requests linger until the block commits, and that's causing problems. On the one hand this gives us the convenience of synchronous calls, on the other it makes benchmarking difficult. We will have to work out a different mechanism for benchmarking where not every request hangs.

**Comment by SCBuergel** [comment]
Thanks @ebuchman! I am running this on a single node (node.js and everything else running on the same machine). I encountered the ECONNRESET after applying that temporary fix mentioned above. That made me think: More generally I'd like the overload behavior to be very well defined, so that a higher level interfacing layer could know when Eris is reaching max load and take appropriate measures, instead of just 100% cpu load, memory usage shooting up and the above mentioned crashes.

**Comment by SCBuergel** [comment]
Now I am getting this issue randomly also in the newly released 0.11.1 without high frequency calling:

[JSON RPC 2.0 Error] Message Id: 1, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid address
/home/someone/.eris/apps/idi/node_modules/eris-db/lib/unsafe.js:116
        data2 = data2[1];
                     ^

TypeError: Cannot read property '1' of undefined
    at fixedCallback (/home/someone/.eris/apps/idi/node_modules/eris-db/lib/unsafe.js:116:22)
    at /home/someone/.eris/apps/idi/node_modules/eris-db/lib/rpc/http.js:79:13
    at httpRequest.onreadystatechange (/home/someone/.eris/apps/idi/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/someone/.eris/apps/idi/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/someone/.eris/apps/idi/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/someone/.eris/apps/idi/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)

**Comment by compleatang** [comment]
Closing this issue for now. If it is still happening, let's track in https://github.com/eris-ltd/eris-contracts.js/issues rather than here.
