### ISSUE TITLE
ECONNREFUSED on running chain

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-cli#883]
Please include in your bug report:

- [ Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
] `docker version`
- [Eris CLI Version: 0.12.0-rc3
 ] `eris version`

- [ubuntu 14.04 VM / windows 8 ] operating system details (osx/windows/linux)
- [when issuing node app.js on a chain with 2 nodes i get the following error]
Error: Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
    at httpRequest.onreadystatechange (/home/infinius/.eris/apps/idi/node_modules/eris-db/lib/rpc/http.js:101:26)
    at dispatchEvent (/home/infinius/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/infinius/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at handleError (/home/infinius/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:516:5)
    at ClientRequest.errorHandler (/home/infinius/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:443:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
both chains are running... I am using smartcontract from the beginner tutorial 
eris chains ls
CHAIN         ON     CONTAINER ID     DATA CONTAINER
advchain1     *      516509217f       0793433e9b
advchain0     *      913378313b       414b33b11d

**Comment by zramsay** [comment]
hi @infinius12345 this is a javascript library issue. Please open issue in https://github.com/eris-ltd/eris-db.js
