### ISSUE TITLE
logrotate results in go error 

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-cli#992]
Please include in your bug report:

- [ ] `docker version`
- [ ] `eris version`
- [ ] `go version` (if applicable)
1.7..1
- [ ] `docker-machine version` (if applicable / !linux)
- [ ] operating system details (osx/windows/linux)
osx
- [ ] what you expected to happen
--logrotate as documented should attach log rotate dependency for keeping the log small
- [ ] what actually happened
```eris chains start chain --init-dir chain --logrotate``` results in error :
```
goroutine 1 [running]:
runtime/debug.Stack(0xb0, 0xb0, 0xc420338580)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/eris-ltd/eris-cli/vendor/github.com/eris-ltd/eris-logger.Bugsnag.SendReport(0xc4202ac1e0, 0xc42017f280, 0x491ae0, 0xc420014120, 0x1, 0x466ae0, 0xc420375bc0)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/vendor/github.com/eris-ltd/eris-logger/hooks_bugsnag.go:90 +0x68c
github.com/eris-ltd/eris-cli/vendor/github.com/eris-ltd/eris-logger.(*Bugsnag).SendReport(0xc4202ae030, 0x491ae0, 0xc420014120, 0xc420375b01, 0x466ae0, 0xc420375b80)
	<autogenerated>:13 +0x78
github.com/eris-ltd/eris-cli/util.SendPanic(0x491ae0, 0xc420014120, 0xc420014120, 0xb08280)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/util/crash_report.go:35 +0x4e
github.com/eris-ltd/eris-cli/cmd.Execute.func1()
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/cmd/eris.go:102 +0x52
panic(0x491ae0, 0xc420014120)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/eris-ltd/eris-cli/chains.bootDependencies(0xc420071da0, 0xc420168700, 0x0, 0x0)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/chains/operate.go:168 +0x65
github.com/eris-ltd/eris-cli/chains.setupChain(0xc420168700, 0xc42015fc20, 0x1)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/chains/operate.go:261 +0xc12
github.com/eris-ltd/eris-cli/chains.StartChain(0xc420168700, 0x0, 0x2)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/chains/operate.go:44 +0x483
github.com/eris-ltd/eris-cli/cmd.StartChain(0x75aea0, 0xc42017e1c0, 0x1, 0x4)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/cmd/chains.go:335 +0xcf
github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x75aea0, 0xc42017e180, 0x4, 0x4, 0x75aea0, 0xc42017e180)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra/command.go:569 +0x411
github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x75d2a0, 0x75f4a0, 0x75a0a0, 0x7580a0)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra/command.go:656 +0x3d8
github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x75d2a0, 0x55acf0, 0x4)
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/vendor/github.com/spf13/cobra/command.go:615 +0x2b
github.com/eris-ltd/eris-cli/cmd.Execute()
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/cmd/eris.go:109 +0x5c
main.main()
	/Users/rguikers/develop/go/src/github.com/eris-ltd/eris-cli/cmd/eris/main.go:10 +0x14
```
- [ ] steps to reproduction
see above

If logratotate still is effective this is a runtime error. If logrotate is deprecated, it should not be in the command help..

**Comment by zramsay** [comment]
definitely a bug. thanks for the report. logrotate should be effective. We'll get this sorted soon.

**Comment by zramsay** [comment]
@rguikers a fix has been merged into  latest develop.

**Comment by rguikers** [comment]
Thanks for the update zack..
